import {describe,it,beforeEach} from 'node:test';import assert from 'node:assert';import {categorize,organize,CATEGORIES} from './categories.mjs';
const NOW=Date.parse('2026-09-24T08:00:00Z');
const base={pubDate:'2026-09-24T08:00:00Z',importance:60};
const mk=(o)=>({...base,...o});
const all35=Array.from({length:35},(_,i)=>{
  const n=i+1;
  if(n===1)return mk({title:'Heavy rain causes flooding in Pune',url:`u${n}`,excerpt:'IMD issues orange alert for heavy rainfall and waterlogging',importance:90});
  if(n===2)return mk({title:'Murder case registered in Koregaon Park',url:`u${n}`,excerpt:'Police arrest suspect in stabbing killing',importance:85});
  if(n===3)return mk({title:'Major traffic jam on Mumbai-Bangalore highway',url:`u${n}`,excerpt:'Gridlock due to pothole repair work near bridge',importance:70});
  if(n===4)return mk({title:'BJP MLA wins election in Pune constituency',url:`u${n}`,excerpt:'Campaign rally draws large crowd for candidate',importance:80});
  if(n===5)return mk({title:'Startup raises funding in Series A round',url:`u${n}`,excerpt:'Investment boost for IT park company valuation',importance:75});
  if(n===6)return mk({title:'University announces admission schedule for engineering',url:`u${n}`,excerpt:'Entrance exam CET results declared for merit list',importance:65});
  if(n===7)return mk({title:'Cricket IPL match at Maharashtra stadium',url:`u${n}`,excerpt:'Team captain scores century in tournament victory',importance:88});
  if(n===8)return mk({title:'Marathi film premiere at city theatre',url:`u${n}`,excerpt:'Actor director attend box office release event',importance:60});
  if(n===9)return mk({title:'Heatwave alert issued by IMD for Pune district',url:`u${n}`,excerpt:'Temperature crosses 42 degrees celsius',importance:92});
  if(n===10)return mk({title:'Robbery at jewellery shop in Camp area',url:`u${n}`,excerpt:'Theft of gold ornaments police file FIR',importance:78});
  if(n===11)return mk({title:'Metro construction causes road diversion',url:`u${n}`,excerpt:'One way traffic signal failure adds congestion',importance:55});
  if(n===12)return mk({title:'Congress corporator protests against policy',url:`u${n}`,excerpt:'Morcha at PMC office over reservation quota',importance:68});
  if(n===13)return mk({title:'Factory expansion creates new job vacancies',url:`u${n}`,excerpt:'Manufacturing hiring for skilled labour positions',importance:72});
  if(n===14)return mk({title:'School fee hike protested by parents association',url:`u${n}`,excerpt:'CBSE curriculum textbook cost increase',importance:58});
  if(n===15)return mk({title:'Football ISL team wins championship trophy',url:`u${n}`,excerpt:'Player scores goal in final match series',importance:82});
  if(n===16)return mk({title:'Bollywood actor visits Pune for shoot',url:`u${n}`,excerpt:'Web series streaming on OTT platform',importance:50});
  if(n===17)return mk({title:'पावसाचा इशारा: पूरस्थिती गंभीर',url:`u${n}`,excerpt:'पाऊसमुळे रस्ते पूरले, नागरिक संकटात',importance:95});
  if(n===18)return mk({title:'हत्या प्रकरण: पोलीसने गुन्हा दाखल केला',url:`u${n}`,excerpt:'आरोपी अटक, न्यायालयात सजा सुनावी',importance:89});
  if(n===19)return mk({title:'यातायात अडचण: मेट्रो बांधकाम सुरू',url:`u${n}`,excerpt:'रस्ता बंद, वाहनचालक संकटात',importance:62});
  if(n===20)return mk({title:'निवडणूक तयारी: पक्षांची युती घोषित',url:`u${n}`,excerpt:'उमेदवारांची यादी जाहीर, प्रचार सुरू',importance:77});
  if(n===21)return mk({title:'उद्योग क्षेत्रात नवीन प्रकल्प मंजूर',url:`u${n}`,excerpt:'निवेश वाढ, रोजगार निर्मिती होईल',importance:73});
  if(n===22)return mk({title:'विद्यापीठ परीक्षा वेळापत्रक जाहीर',url:`u${n}`,excerpt:'सराव सुरू, निकाल महिन्यात येईल',importance:63});
  if(n===23)return mk({title:'क्रिकेट रणजी स्पर्धा: महाराष्ट्र जिंकला',url:`u${n}`,excerpt:'कप्तानाचे शतक, टिमचे उत्कृष्ट कारकीर्द',importance:86});
  if(n===24)return mk({title:'नाट्य उत्सव: प्रसिद्ध संचालकांचे नाट्य',url:`u${n}`,excerpt:'रंगभूमीवर कलाकारांची विशेष उपस्थिती',importance:52});
  if(n===25)return mk({title:'Storm warning for coastal Maharashtra',url:`u${n}`,excerpt:'Cyclone approaching red alert issued',importance:94});
  if(n===26)return mk({title:'Building collapse in old city area',url:`u${n}`,excerpt:'Fire brigade rescue operation underway',importance:87});
  if(n===27)return mk({title:'Auto strike hits commuters hard',url:`u${n}`,excerpt:'PMPML bus service increased to manage rush',importance:67});
  if(n===28)return mk({title:'New bill passed in state assembly',url:`u${n}`,excerpt:'Ordinance on municipal governance notified',importance:74});
  if(n===29)return mk({title:'GST collection rises in quarter',url:`u${n}`,excerpt:'Trade export import figures improve',importance:69});
  if(n===30)return mk({title:'NEET JEE results declared today',url:`u${n}`,excerpt:'Cutoff marks for medical engineering seats',importance:81});
  if(n===31)return mk({title:'Kabaddi tournament final this weekend',url:`u${n}`,excerpt:'Team captain leads squad to victory',importance:79});
  if(n===32)return mk({title:'Art exhibition showcases local heritage',url:`u${n}`,excerpt:'Culture festival at exhibition hall',importance:48});
  if(n===33)return mk({title:'Duplicate URL test story',url:'u1',excerpt:'Should be dropped by dedupe',importance:10});
  if(n===34)return mk({title:'Heavy rain causes flooding in Pune',url:'u34',excerpt:'Duplicate title different URL',importance:10});
  return mk({title:`Generic Pune Local story ${n}`,url:`u${n}`,excerpt:'Local update for residents',importance:40});
});

describe('categorize',()=>{
  it('Weather English keywords',()=>assert.strictEqual(categorize({title:'Heavy rain causes flooding',excerpt:'IMD orange alert'}),'Weather'));
  it('Weather Marathi keywords',()=>assert.strictEqual(categorize({title:'पावसाचा इशारा',excerpt:'पूरस्थिती गंभीर'}),'Weather'));
  it('Crime English',()=>assert.strictEqual(categorize({title:'Murder case registered',excerpt:'Police arrest suspect'}),'Crime & Safety'));
  it('Crime Marathi',()=>assert.strictEqual(categorize({title:'हत्या प्रकरण',excerpt:'पोलीसने गुन्हा दाखल केला'}),'Crime & Safety'));
  it('Traffic English',()=>assert.strictEqual(categorize({title:'Traffic jam on highway',excerpt:'Pothole repair work'}),'Traffic'));
  it('Traffic Marathi',()=>assert.strictEqual(categorize({title:'यातायात अडचण',excerpt:'मेट्रो बांधकाम सुरू'}),'Traffic'));
  it('Politics English',()=>assert.strictEqual(categorize({title:'Election campaign rally',excerpt:'BJP candidate manifesto'}),'Politics'));
  it('Politics Marathi',()=>assert.strictEqual(categorize({title:'निवडणूक तयारी',excerpt:'उमेदवारांची यादी'}),'Politics'));
  it('Business English',()=>assert.strictEqual(categorize({title:'Startup funding round',excerpt:'Investment in company'}),'Business'));
  it('Business Marathi',()=>assert.strictEqual(categorize({title:'उद्योग क्षेत्रात नवीन प्रकल्प',excerpt:'निवेश वाढ'}),'Business'));
  it('Education English',()=>assert.strictEqual(categorize({title:'University admission schedule',excerpt:'Entrance exam results'}),'Education'));
  it('Education Marathi',()=>assert.strictEqual(categorize({title:'विद्यापीठ परीक्षा वेळापत्रक',excerpt:'सराव सुरू'}),'Education'));
  it('Sports cricket English',()=>assert.strictEqual(categorize({title:'Cricket IPL match',excerpt:'Team captain century'}),'Sports'));
  it('Sports cricket Marathi',()=>assert.strictEqual(categorize({title:'क्रिकेट रणजी स्पर्धा',excerpt:'कप्तानाचे शतक'}),'Sports'));
  it('Entertainment English',()=>assert.strictEqual(categorize({title:'Film premiere event',excerpt:'Actor director attend'}),'Entertainment'));
  it('Entertainment Marathi',()=>assert.strictEqual(categorize({title:'नाट्य उत्सव',excerpt:'संचालकांचे नाट्य'}),'Entertainment'));
  it('Ambiguous words ignored',()=>assert.strictEqual(categorize({title:'Court fine for construction',excerpt:'Bridge share market job'}),'Pune Local'));
  it('Existing category boost',()=>assert.strictEqual(categorize({title:'Generic',excerpt:'',existingCategory:'Sports'}),'Sports'));
});

describe('organize',()=>{
  it('Default limit 25 cap',()=>{const r=organize(all35,{now:NOW});assert.strictEqual(r.stories.length,25);assert.strictEqual(r.hasMore,true);});
  it('Limit clamped 20 min',()=>{const r=organize(all35,{limit:5,now:NOW});assert.strictEqual(r.stories.length,20);});
  it('Limit clamped 30 max',()=>assert.strictEqual(organize(all35,{limit:50,now:NOW}).stories.length,30));
  it('Category pages retain all 35 related stories',()=>{const items=Array.from({length:35},(_,i)=>mk({title:'Pune cricket report '+i,url:'https://example.com/'+i}));const r=organize(items,{category:'Sports',now:NOW});assert.strictEqual(r.stories.length,35);assert.strictEqual(r.hasMore,false);});
  it('Category counts include empty sections',()=>{const r=organize([mk({title:'Pune cricket update',url:'https://example.com/a'})],{now:NOW});assert.deepStrictEqual(r.categoryCounts.map(c=>c.name),CATEGORIES);assert.strictEqual(r.categoryCounts.find(c=>c.name==='Weather').count,0);});
  it('Duplicate URL dropped',()=>{const r=organize(all35,{category:'All',now:NOW});const urls=r.stories.map(s=>s.url);assert.strictEqual(new Set(urls).size,urls.length);});
  it('Duplicate title dropped',()=>{const r=organize(all35,{category:'All',now:NOW});const titles=r.stories.map(s=>s.title.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim());assert.strictEqual(new Set(titles).size,titles.length);});
  it('Invalid dates dropped',()=>{const bad=[...all35,mk({title:'Bad date',url:'ubad',pubDate:'invalid'})];const r=organize(bad,{category:'All',now:NOW});assert.ok(!r.stories.find(s=>s.title==='Bad date'));});
  it('Important + fresh ordering impact',()=>{const r=organize(all35,{category:'All',sort:'impact',now:NOW});const top=r.stories[0];assert.ok(top.importance>=90);});
  it('Latest sort by time',()=>{const r=organize(all35,{category:'All',sort:'latest',now:NOW});assert.ok(r.stories[0].pubDate>=r.stories[1].pubDate);});
  it('Weather category filter',()=>{const r=organize(all35,{category:'Weather',now:NOW});assert.ok(r.stories.every(s=>s.section==='Weather'));assert.strictEqual(r.hasMore,false);});
  it('Sports category filter',()=>{const r=organize(all35,{category:'Sports',now:NOW});assert.ok(r.stories.every(s=>s.section==='Sports'));});
  it('Marathi classification Weather',()=>{const r=organize(all35,{category:'Weather',now:NOW});assert.ok(r.stories.some(s=>/पावस|पाऊस/.test(s.title)));});
  it('English classification Sports cricket',()=>{const r=organize(all35,{category:'Sports',now:NOW});assert.ok(r.stories.some(s=>/cricket|ipl|ranji/i.test(s.title)));});
  it('Total count reflects filtered',()=>{const r=organize(all35,{category:'Weather',now:NOW});assert.strictEqual(r.totalCount,r.stories.length);});
  it('Section assigned to each story',()=>{const r=organize(all35,{now:NOW});assert.ok(r.stories.every(s=>CATEGORIES.includes(s.section)));});
  it('Limit 30 with category All',()=>{const r=organize(all35,{category:'All',limit:30,now:NOW});assert.strictEqual(r.stories.length,30);});
  it('Limit 20 with category All',()=>{const r=organize(all35,{category:'All',limit:20,now:NOW});assert.strictEqual(r.stories.length,20);});
  it('HasMore false when category known',()=>{const r=organize(all35,{category:'Sports',now:NOW});assert.strictEqual(r.hasMore,false);});
  it('HasMore true when uncapped exceeds',()=>{const r=organize(all35,{category:'All',limit:10,now:NOW});assert.strictEqual(r.hasMore,true);});
  it('Importance ranks otherwise equivalent stories',()=>{const r=organize([mk({title:'Pune update A',url:'a',importance:50}),mk({title:'Pune update B',url:'b',importance:90})],{now:NOW});assert.strictEqual(r.stories[0].url,'b');});
  it('Empty input returns empty',()=>{const r=organize([],{now:NOW});assert.deepStrictEqual(r.stories,[]);assert.strictEqual(r.totalCount,0);});
  it('Non-array input handled',()=>{const r=organize(null,{now:NOW});assert.deepStrictEqual(r.stories,[]);});
  it('Missing title skipped',()=>{const r=organize([{pubDate:'2026-09-24T08:00:00Z',url:'u'}],{now:NOW});assert.strictEqual(r.stories.length,0);});
});

it('Public service disruption outranks promotional admissions with equal base importance',()=>{const r=organize([mk({title:'College announces admissions open',url:'promo',importance:100}),mk({title:'Pune water supply disrupted by pipeline burst',url:'service',importance:100})],{now:NOW});assert.strictEqual(r.stories[0].url,'service');});
it('Promotional awards stay available in categories',()=>{const item=mk({title:'School earns Great Place to Work certification',url:'award',importance:100});const r=organize([item],{category:'Education',now:NOW});assert.equal(r.stories.length,1);});
