import {test} from 'node:test';
import assert from 'node:assert/strict';
import {locate,normalize,selectStories,rangeStart,dayIST,safeUrl} from './news.mjs';
const now=Date.parse('2026-09-22T06:00:00Z');
const raw=(extra={})=>({article_id:'test',title:'Pune road works announced in Baner',description:'Publisher test fixture',link:'https://example.org/news?utm_source=test',pubDate:'2026-09-22 04:00:00',source_name:'Test publisher',category:['domestic'],...extra});
const news=(title,date,areas=['Baner'])=>({id:title,title,excerpt:'Test fixture',source:'Test',pubDate:date,areas,category:'Transport'});
test('Areas use word boundaries and support Marathi',()=>{assert.deepEqual(locate('Pune campaign launched'),['Pune · area unspecified']);assert.deepEqual(locate('बाणेर आणि वाकड येथे काम'),['Baner','Wakad']);});
test('Unknown area is never guessed',()=>assert.deepEqual(locate('Pune civic meeting'),['Pune · area unspecified']));
test('Original publisher headline and image attribution retained',()=>{const r=normalize(raw({image_url:'https://example.org/photo.jpg'}),now);assert.equal(r.title,raw().title);assert.equal(r.imageUrl,'https://example.org/photo.jpg');assert.equal(r.url,'https://example.org/news');});
test('Invalid, future and unrelated reports rejected',()=>{assert.equal(normalize(raw({pubDate:'invalid'}),now),null);assert.equal(normalize(raw({pubDate:'2026-10-01 00:00:00'}),now),null);assert.equal(normalize(raw({title:'Delhi stocks report',description:''}),now),null);});
test('Unsafe image and article URLs excluded',()=>{assert.equal(safeUrl('javascript:alert(1)'),null);assert.equal(safeUrl('http://127.0.0.1/a'),null);assert.equal(normalize(raw({image_url:'javascript:x'}),now).imageUrl,null);});
test('Three day window is calendar days in India',()=>{assert.equal(new Date(rangeStart(now)).toISOString(),'2026-09-19T18:30:00.000Z');assert.equal(dayIST('2026-09-21T18:30:00Z'),'2026-09-22');});
const history=[news('Test today','2026-09-22T01:00:00Z'),news('Test yesterday','2026-09-21T01:00:00Z'),news('Test two days ago','2026-09-20T01:00:00Z'),news('Test expired','2026-09-19T01:00:00Z')];
test('Sparse today includes preceding two days only',()=>{const r=selectStories(history,{},now);assert.equal(r.stories.length,3);assert.equal(r.meta.showingPreviousDays,true);});
test('Today mode never falls back',()=>assert.equal(selectStories(history,{period:'today'},now).stories.length,1));
test('Six today hides previous days in smart mode',()=>{const today=Array.from({length:6},(_,i)=>news('Test news '+i,'2026-09-22T01:00:00Z'));assert.equal(selectStories([...today,...history.slice(1)],{},now).stories.length,6);});
test('Area selection affects fallback before counting',()=>{const many=Array.from({length:6},(_,i)=>news('Test Hinjewadi '+i,'2026-09-22T01:00:00Z',['Hinjewadi']));const r=selectStories([...many,...history],{area:'Baner'},now);assert.equal(r.stories.length,3);assert.equal(r.meta.todayCount,1);});
test('Identical headlines are not repeated',()=>assert.equal(selectStories([history[0],{...history[0],id:'copy'}],{},now).stories.length,1));
test('Explicit 3-day mode includes earlier reports despite busy day',()=>{const today=Array.from({length:6},(_,i)=>news('Test news '+i,'2026-09-22T01:00:00Z'));assert.equal(selectStories([...today,...history.slice(1)],{period:'3d'},now).stories.length,8);});
